# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dis_grad <- function(phi_x, Y, theta, lambda, tau, S, M) {
    .Call(`_DisRFKQR_dis_grad`, phi_x, Y, theta, lambda, tau, S, M)
}

ADMM <- function(phi_x, Y, grad_dif, r_0, u_0, lambda, tau, beta, S, max_iter) {
    .Call(`_DisRFKQR_ADMM`, phi_x, Y, grad_dif, r_0, u_0, lambda, tau, beta, S, max_iter)
}

DKQR_RF <- function(phi_x, Y, r_0, u_0, lambda, tau, M, beta, S, max_iter_admm, max_iter_dis) {
    .Call(`_DisRFKQR_DKQR_RF`, phi_x, Y, r_0, u_0, lambda, tau, M, beta, S, max_iter_admm, max_iter_dis)
}

